---

- name: ensure EPEL is enabled
  become: true
  yum:
    name: epel-release
    state: present

- name: install tools
  become: true
  yum: pkg={{ item }} state=latest
  with_items:
    - gcc-c++
    - autoconf
    - automake
    - nodejs

- name: ensure link /usr/bin/node -> /usr/bin/nodejs exists
  become: true
  file:
    src: /usr/bin/node
    dest: /usr/bin/nodejs
    state: link

- name: install yarn repo
  get_url:
    url: https://dl.yarnpkg.com/rpm/yarn.repo
    dest: /etc/yum.repos.d/yarn.repo

- name: install yarn
  yum:
    name: yarn
    state: present
