---

- name: get os specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: vars

#- name: ensure user superset exists
#  user:
#    name: superset
#    state: present
#    home: /opt/superset
#    shell: /sbin/nologin
#    comment: superset

- name: include task for CentOS7
  import_tasks: CentOS7.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '7'
  tags: include

- name: install virtualenv
  pip:
    name: virtualenv
    state: present

- name: install setuptools
  pip: 
    name: setuptools
    state: latest

- name: install pip
  pip: 
    name: pip
    state: latest

- name: install superset
  pip: 
    name: superset
    state: latest
